management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=health,info,prometheus
management.info.env.enabled=true
management.info.git.mode=full
management.info.java.enabled=true
management.info.os.enabled=true
# HTTP server for the actuator endpoints (health / info / prometheus)
server.port=9001
spring.application.name=sluice-client
spring.config.import=optional:classpath:git.properties,optional:classpath:META-INF/build-info.properties
spring.main.keep-alive=true
spring.threads.virtual.enabled=true
